import json
import re

from src.analyzer.rule_based_flags import detect_rule_based_flags

# Matches the exact <document>...</document> wrapping build_user_prompt()
# applies in src/analyzer/prompts.py.
_DOCUMENT_TAG_RE = re.compile(r"<document>\n?(.*?)\n?</document>", re.DOTALL)

_CONTEXT_KEYWORDS = {
    "legal": ("contract", "lease", "agreement", "contratto", "clausola", "termini"),
    "work": ("memo", "deadline", "report", "team", "riunione", "progetto"),
    "personal": ("dear", "caro", "cara", "famiglia", "family"),
}

_ANALYSIS_EXPLANATION = {
    "it": (
        "[Modalità demo] Nessuna credenziale Azure OpenAI configurata: questa spiegazione "
        "è simulata, non generata da un vero modello AI. I punti di attenzione qui sotto "
        "restano reali: individuati da un controllo automatico basato su regole sul testo "
        "effettivamente estratto dal documento."
    ),
    "en": (
        "[Demo mode] No Azure OpenAI credentials configured: this explanation is simulated, "
        "not generated by a real AI model. The flags below are still real, detected by an "
        "automatic rule-based check against the actual extracted document text."
    ),
}

_ANALYSIS_SUMMARY = {
    "it": "Riassunto simulato (modalità demo) — nessuna analisi AI reale è stata eseguita.",
    "en": "Simulated summary (demo mode) — no real AI analysis was performed.",
}

_COMPARISON_SUMMARY = {
    "it": (
        "[Modalità demo] Nessuna credenziale Azure OpenAI configurata: questo confronto è "
        "simulato, non generato da un vero modello AI."
    ),
    "en": (
        "[Demo mode] No Azure OpenAI credentials configured: this comparison is simulated, "
        "not generated by a real AI model."
    ),
}

_DEFAULT_LANGUAGE = "en"


def _extract_document_text(user_content: str) -> str:
    match = _DOCUMENT_TAG_RE.search(user_content)
    return match.group(1) if match else user_content


def _extract_language(user_content: str) -> str:
    match = re.search(r"Respond in (\w+)", user_content)
    if not match:
        return _DEFAULT_LANGUAGE
    return "it" if match.group(1) == "Italian" else _DEFAULT_LANGUAGE


def _detect_context(text: str) -> str:
    lowered = text.lower()
    for context, keywords in _CONTEXT_KEYWORDS.items():
        if any(keyword in lowered for keyword in keywords):
            return context
    return "other"


def _build_analysis_response(user_content: str) -> dict:
    document_text = _extract_document_text(user_content)
    language = _extract_language(user_content)
    flags = detect_rule_based_flags(document_text)
    return {
        "detected_context": _detect_context(document_text),
        "plain_explanation": _ANALYSIS_EXPLANATION[language],
        "summary": _ANALYSIS_SUMMARY[language],
        "red_flags": [flag.model_dump() for flag in flags],
    }


def _build_comparison_response(user_content: str) -> dict:
    language = _extract_language(user_content)
    return {"summary": _COMPARISON_SUMMARY[language], "differences": []}


class _FakeMessage:
    def __init__(self, content: str):
        self.content = content


class _FakeChoice:
    def __init__(self, content: str):
        self.message = _FakeMessage(content)


class _FakeCompletion:
    def __init__(self, content: str):
        self.choices = [_FakeChoice(content)]


class _FakeCompletions:
    def create(self, model, response_format, messages):  # noqa: ARG002 - matches the real client's signature
        system_content = next(m["content"] for m in messages if m["role"] == "system")
        user_content = next(m["content"] for m in messages if m["role"] == "user")

        # SYSTEM_PROMPT and COMPARISON_SYSTEM_PROMPT (src/analyzer/prompts.py,
        # comparison_prompts.py) each describe their own JSON schema; "differences"
        # only appears in the comparison one, so it's a reliable discriminator.
        if "differences" in system_content:
            payload = _build_comparison_response(user_content)
        else:
            payload = _build_analysis_response(user_content)

        return _FakeCompletion(json.dumps(payload))


class _FakeChat:
    def __init__(self):
        self.completions = _FakeCompletions()


class DemoAIClient:
    """Fake Azure OpenAI-shaped client used when no real credentials are configured.

    Duck-types the same surface DocumentAnalyzer/DocumentComparator call
    (client.chat.completions.create(...)) so it's a drop-in replacement for
    the real AzureOpenAI client. Red flags come from the real rule-based
    detector run against the real document text -- only the narrative
    explanation is templated, and it always says so explicitly.
    """

    def __init__(self):
        self.chat = _FakeChat()
