import base64
import logging
import re
from contextlib import asynccontextmanager
from pathlib import Path, PurePosixPath

from fastapi import Depends, FastAPI, File, Form, HTTPException, Request, UploadFile
from fastapi.responses import FileResponse, JSONResponse, Response
from fastapi.staticfiles import StaticFiles
from slowapi import Limiter, _rate_limit_exceeded_handler
from slowapi.errors import RateLimitExceeded
from slowapi.util import get_remote_address

from src.analyzer.document_analyzer import AnalysisError
from src.analyzer.document_comparator import ComparisonError, DocumentComparator
from src.api.config import Settings, get_settings
from src.api.dependencies import get_document_comparator, get_extractor_factory, get_pipeline
from src.extractors.base import ExtractionError
from src.extractors.factory import ExtractorFactory, UnsupportedFileTypeError
from src.pipeline import DocumentAnalysisPipeline


_logger = logging.getLogger("file_analyzer.api")


@asynccontextmanager
async def lifespan(app: FastAPI):
    if get_settings().is_demo_mode:
        _logger.warning(
            "Running in DEMO MODE: no AZURE_OPENAI_ENDPOINT/AZURE_OPENAI_API_KEY configured. "
            "Analysis and comparison responses are simulated, not generated by a real AI model."
        )
    yield


app = FastAPI(title="File Analyzer", lifespan=lifespan)

_FRONTEND_DIR = Path(__file__).resolve().parent.parent.parent / "frontend"
app.mount("/static", StaticFiles(directory=_FRONTEND_DIR), name="static")


@app.middleware("http")
async def no_cache_static_assets(request: Request, call_next):
    # Static assets have no versioned filenames, so without an explicit
    # header browsers apply heuristic caching (based on Last-Modified) and
    # can silently keep serving a pre-deploy JS/CSS bundle. no-cache forces
    # revalidation (a cheap 304 via ETag) on every load instead.
    response = await call_next(request)
    if request.url.path.startswith("/static/"):
        response.headers["Cache-Control"] = "no-cache"
    return response

limiter = Limiter(key_func=get_remote_address)
app.state.limiter = limiter
app.add_exception_handler(RateLimitExceeded, _rate_limit_exceeded_handler)

# Every domain error maps to the same HTTP status code everywhere it can be
# raised, so endpoints just raise it and let one handler do the mapping
# instead of repeating the same try/except in every route.
_ERROR_STATUS_CODES: list[tuple[type[Exception], int]] = [
    (UnsupportedFileTypeError, 415),
    (ExtractionError, 422),
    (AnalysisError, 502),
    (ComparisonError, 502),
]


def _status_code_for(exc: Exception) -> int | None:
    for exc_type, status_code in _ERROR_STATUS_CODES:
        if isinstance(exc, exc_type):
            return status_code
    return None


def _register_error_handler(exc_type: type[Exception]) -> None:
    @app.exception_handler(exc_type)
    async def _handler(request: Request, exc: Exception) -> JSONResponse:  # noqa: ARG001
        return JSONResponse(status_code=_status_code_for(exc), content={"detail": str(exc)})


for _exc_type, _ in _ERROR_STATUS_CODES:
    _register_error_handler(_exc_type)


def _rate_limit() -> str:
    return f"{get_settings().rate_limit_per_minute}/minute"

_UNSAFE_FILENAME_CHARS = re.compile(r"[^A-Za-z0-9._-]")


@app.get("/")
def index() -> FileResponse:
    return FileResponse(_FRONTEND_DIR / "index.html")


def _report_filename(original_filename: str, extension: str = "pdf") -> str:
    stem = PurePosixPath(original_filename.replace("\\", "/")).stem
    safe_stem = _UNSAFE_FILENAME_CHARS.sub("_", stem) or "report"
    return f"{safe_stem}-report.{extension}"


@app.get("/health")
def health() -> dict:
    settings = get_settings()
    return {"status": "ok", "demo_mode": settings.is_demo_mode, "ai_provider": settings.ai_provider}


async def _read_within_size_limit(file: UploadFile, settings: Settings) -> bytes:
    # Fast path: reject oversized uploads before buffering the whole body.
    if file.size is not None and file.size > settings.max_file_size_bytes:
        raise HTTPException(status_code=413, detail="File exceeds the maximum allowed size")

    file_bytes = await file.read()

    # Fallback for clients/servers that don't populate .size.
    if len(file_bytes) > settings.max_file_size_bytes:
        raise HTTPException(status_code=413, detail="File exceeds the maximum allowed size")

    return file_bytes


@app.post("/extract")
@limiter.limit(_rate_limit)
async def extract(
    request: Request,
    file: UploadFile,
    factory: ExtractorFactory = Depends(get_extractor_factory),
) -> dict[str, str]:
    settings = get_settings()
    file_bytes = await _read_within_size_limit(file, settings)

    extractor = factory.get_extractor(file.filename or "upload", file.content_type)
    raw_text = extractor.extract(file_bytes, file.filename or "upload")

    return {"text": raw_text.content}


@app.post("/analyze")
@limiter.limit(_rate_limit)
async def analyze(
    request: Request,
    file: UploadFile,
    language: str = Form("it"),
    pipeline: DocumentAnalysisPipeline = Depends(get_pipeline),
) -> Response:
    settings = get_settings()
    file_bytes = await _read_within_size_limit(file, settings)

    pdf_bytes = pipeline.run(
        file_bytes=file_bytes,
        filename=file.filename or "upload",
        content_type=file.content_type,
        language=language,
    )

    report_filename = _report_filename(file.filename or "upload")
    return Response(
        content=pdf_bytes,
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{report_filename}"'},
    )


@app.post("/analyze/review")
@limiter.limit(_rate_limit)
async def analyze_review(
    request: Request,
    file: UploadFile,
    language: str = Form("it"),
    extracted_text: str | None = Form(None),
    pipeline: DocumentAnalysisPipeline = Depends(get_pipeline),
) -> dict:
    if extracted_text:
        # The frontend already extracted this text for the preview panel --
        # reuse it instead of re-running (potentially OCR-heavy) extraction.
        analysis, pdf_bytes = pipeline.run_with_analysis_from_text(
            text=extracted_text,
            filename=file.filename or "upload",
            language=language,
        )
    else:
        settings = get_settings()
        file_bytes = await _read_within_size_limit(file, settings)
        analysis, pdf_bytes = pipeline.run_with_analysis(
            file_bytes=file_bytes,
            filename=file.filename or "upload",
            content_type=file.content_type,
            language=language,
        )

    return {
        "analysis": analysis.model_dump(),
        "pdf_base64": base64.b64encode(pdf_bytes).decode("ascii"),
    }


@app.post("/analyze/markdown")
@limiter.limit(_rate_limit)
async def analyze_markdown(
    request: Request,
    file: UploadFile,
    language: str = Form("it"),
    pipeline: DocumentAnalysisPipeline = Depends(get_pipeline),
) -> Response:
    settings = get_settings()
    file_bytes = await _read_within_size_limit(file, settings)
    filename = file.filename or "upload"

    analysis, _ = pipeline.run_with_analysis(
        file_bytes=file_bytes,
        filename=filename,
        content_type=file.content_type,
        language=language,
    )

    markdown = pipeline.render_markdown(analysis, filename)
    report_filename = _report_filename(filename, extension="md")
    return Response(
        content=markdown,
        media_type="text/markdown; charset=utf-8",
        headers={"Content-Disposition": f'attachment; filename="{report_filename}"'},
    )


@app.post("/analyze/batch")
@limiter.limit(_rate_limit)
async def analyze_batch(
    request: Request,
    files: list[UploadFile] = File(...),
    language: str = Form("it"),
    pipeline: DocumentAnalysisPipeline = Depends(get_pipeline),
) -> dict:
    settings = get_settings()

    if len(files) > settings.max_batch_files:
        raise HTTPException(
            status_code=413,
            detail=f"Batch exceeds the maximum of {settings.max_batch_files} files",
        )

    results = []
    for file in files:
        filename = file.filename or "upload"
        try:
            file_bytes = await _read_within_size_limit(file, settings)
            analysis, pdf_bytes = pipeline.run_with_analysis(
                file_bytes=file_bytes,
                filename=filename,
                content_type=file.content_type,
                language=language,
            )
            results.append(
                {
                    "filename": filename,
                    "status": "ok",
                    "analysis": analysis.model_dump(),
                    "pdf_base64": base64.b64encode(pdf_bytes).decode("ascii"),
                }
            )
        except HTTPException as exc:
            results.append({"filename": filename, "status": "error", "status_code": exc.status_code, "detail": exc.detail})
        except (UnsupportedFileTypeError, ExtractionError, AnalysisError) as exc:
            results.append(
                {"filename": filename, "status": "error", "status_code": _status_code_for(exc), "detail": str(exc)}
            )

    return {"results": results}


@app.post("/compare")
@limiter.limit(_rate_limit)
async def compare(
    request: Request,
    file_a: UploadFile,
    file_b: UploadFile,
    language: str = Form("it"),
    factory: ExtractorFactory = Depends(get_extractor_factory),
    comparator: DocumentComparator = Depends(get_document_comparator),
) -> dict:
    settings = get_settings()
    bytes_a = await _read_within_size_limit(file_a, settings)
    bytes_b = await _read_within_size_limit(file_b, settings)
    name_a = file_a.filename or "version_a"
    name_b = file_b.filename or "version_b"

    extractor_a = factory.get_extractor(name_a, file_a.content_type)
    text_a = extractor_a.extract(bytes_a, name_a).content
    extractor_b = factory.get_extractor(name_b, file_b.content_type)
    text_b = extractor_b.extract(bytes_b, name_b).content
    comparison = comparator.compare(text_a, text_b, language=language)

    return {"comparison": comparison.model_dump()}
